// <auto-generated />
using System;
using BookingTicket.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingTicket.Entities.Migrations
{
    [DbContext(typeof(BookingTicketContext))]
    [Migration("20191004153534_UpdateDb")]
    partial class UpdateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("BookingTicket.Entities.Models.NguoiDung", b =>
                {
                    b.Property<long>("UserID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Avatar")
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("DiaChi")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("GioiTinh");

                    b.Property<string>("HoTen")
                        .HasColumnType("varchar(150)");

                    b.Property<string>("MatKhau")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("NgaySinh");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("UserID");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("BookingTicket.Entities.Models.ThongTinDatCho", b =>
                {
                    b.Property<long>("MadatCho")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CMND")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("HoTenNguoiDat")
                        .HasColumnType("varchar(150)");

                    b.Property<long>("MaDieuHanh");

                    b.Property<long?>("MaKH");

                    b.Property<DateTime>("NgayDat");

                    b.Property<string>("SDT")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SoLuongVe");

                    b.HasKey("MadatCho");

                    b.HasIndex("MaKH");

                    b.ToTable("ThongTinDatCho");
                });

            modelBuilder.Entity("BookingTicket.Entities.Models.ThongTinDatCho", b =>
                {
                    b.HasOne("BookingTicket.Entities.Models.NguoiDung", "NguoiDatCho")
                        .WithMany("DanhSachDatCho")
                        .HasForeignKey("MaKH");
                });
#pragma warning restore 612, 618
        }
    }
}
